version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.0-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app/web:delegated
    ports:
      - 80:80
      - 443:443
    depends_on:
      # - redis
      - mariadb
  mariadb:
    image: mariadb:10.7
    # restart: always
    ports:
      - 3306:3306
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      - ./:/app:delegated
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=citizix_user
      - MYSQL_DATABASE=citizix_db
