<?php 
use yii\bootstrap\BootstrapAsset;
use yii\helpers\Url;
use kartik\export\ExportMenu;
use dosamigos\gridexport\ExportGridButton;
use dosamigos\exportable\ExportableButton; 
use dosamigos\exportable\helpers\TypeHelper; 
?>
<div class="panel panel-primary">
    <!-- Default panel contents -->
    <div class="panel-heading"> <h3 class="panel-title"><?= $heading ?></h3></div>
    <div id="laporan-format" class="panel-body">
        <div class="pull-right">
        <?php 
        // echo ExportGridButton::widget([
        //     'label' => 'Export Bookings',
        //     'selector' => '#laporan-format > table',
        //     'split' => true,
        //     'exportClientOptions' => [
        //         // 'ignoredColumns' => [0, 7],
        //         'useDataUri' => true,
        //         // 'url' => \yii\helpers\Url::to('download')
        //     ]
        // ]);
        echo ExportMenu::widget([
            'dataProvider' => $data,
            'enableFormatter' => true,
            'showColumnSelector' => false,
            'fontAwesome' => true,
            // 'exportConfig' => [
            //     GridView::HTML => ['filename' => $heading,],
            //     GridView::CSV => ['filename' => $heading,],
            //     GridView::TEXT => ['filename' => $heading,],
            //     GridView::EXCEL => ['filename' => $heading,], 
            //     GridView::PDF => [
            //         'label' => 'PDF',
            //         'showHeader' => true,
            //         'showPageSummary' => true,
            //         'showFooter' => true,
            //         'showCaption' => true,
            //         'filename' => $heading,
            //         'alertMsg' => 'The PDF export file will be generated for download.',
            //         'options' => ['title' => 'Portable Document Format'],
            //         'mime' => 'application/pdf',
            //         'config' => [
            //             'mode' => 'c',
            //             'format' => 'A4-L',
            //             'destination' => 'D',
            //             'marginTop' => 20,
            //             'marginBottom' => 20,
            //             'cssInline' => '.kv-wrap{padding:20px;}' .
            //                 '.kv-align-center{text-align:center;}' .
            //                 '.kv-align-left{text-align:left;}' .
            //                 '.kv-align-right{text-align:right;}' .
            //                 '.kv-align-top{vertical-align:top!important;}' .
            //                 '.kv-align-bottom{vertical-align:bottom!important;}' .
            //                 '.kv-align-middle{vertical-align:middle!important;}' .
            //                 '.kv-page-summary{border-top:4px double #ddd;font-weight: bold;}' .
            //                 '.kv-table-footer{border-top:4px double #ddd;font-weight: bold;}' .
            //                 '.kv-table-caption{font-size:1.5em;padding:8px;border:1px solid #ddd;border-bottom:none;}',
            //             'methods' => [
            //                 'SetHeader' => $heading,
            //                 'SetFooter' => '<li role="presentation" class="dropdown-footer">Generated by econsole, '.date('Y-m-d H-i-s T').'</li>',
            //             ],
            //             'options' => [
            //                 'title' => $heading,
            //                 'subject' => 'PDF export generated by econsole',
            //                 'keywords' => 'grid, export, yii2-grid, pdf'
            //             ],
            //             'contentBefore'=>'',
            //             'contentAfter'=>''
            //         ]
            //     ],
            //     GridView::JSON => ['filename' => $heading,],
            // ],
            'columns' => [
                [
                    'label' => 'Kode Rekening',
                    'width' => '10%',
                    'hAlign' => 'center',
                    'value' => function($model){
                        return $model['kd_rek_1'].$model['kd_rek_2'].$model['kd_rek_3'];
                    }
                ],
                [
                    'label' => 'Uraian',
                    'attribute' => 'nm_akrual_3',
                    'format' => 'raw',
                    'value' => function($model){
                        if($model['nm_akrual_3'] == '[--Rekening Tidak Terdaftar--]'){
                            return '<code>'.$model['nm_akrual_3'].'</code>';
                        }
                        return $model['nm_akrual_3'];
                    }
                ],
                [
                    'attribute' => 'realisasi_sebelum',
                    'label' => 'Sebelum Eliminasi',
                    'format' => 'decimal',
                    'hAlign' => 'right',
                    'pageSummary' => true,
                    'value' => function($model){
                        return $model['realisasi_sebelum'] ? $model['realisasi_sebelum'] : 0;
                    }
                ],
                [
                    'attribute' => 'realisasi_sesudah',
                    'label' => 'Sesudah Eliminasi',
                    'format' => 'decimal',
                    'hAlign' => 'right',
                    'pageSummary' => true,
                    'value' => function($model){
                        return $model['realisasi_sesudah'] ? $model['realisasi_sesudah'] : 0;
                    }
                ],
            ]
        ]);
        ?>
        </div>
    </div>

    <!-- Table -->
    <table class="table table-striped table-bordered table-hover"> 
        <thead> 
            <tr> 
                <th style="text-align:center;">Kode Akun</th> 
                <th style="text-align:left;">Uraian</th> 
                <th style="text-align:right;">Saldo Awal</th> 
                <!-- <th style="text-align:right;">Eliminasi</th> -->
                <th style="text-align:right;">Saldo Konsolidasi</th> 
            </tr> 
        </thead> 
        <tbody>
            <?php
                $kdAkun1 = 0;
                $kdAkun2 = 0;
                $totalSebelum2 = $totalSesudah2 = $totalSebelum1 = $totalSesudah1 = $totalAkun4Sebelum = $totalAkun4Sesudah = $totalAkun5Sebelum = $totalAkun5Sesudah =
                $totalAkun61Sebelum = $totalAkun61Sesudah = $totalAkun62Sebelum = $totalAkun62Sesudah = $totalAkun71Sebelum = $totalAkun71Sesudah = $totalAkun72Sebelum = $totalAkun72Sesudah = 0;
                foreach($data->getModels() as $model):
                    if($kdAkun1 != $model['kd_rek_1'] && $kdAkun1 != 0){
                        echo renderTotalAkun2($lastModel, number_format($totalSebelum2), number_format($totalSesudah2));
                        $totalSebelum2 = 0; $totalSesudah2 = 0;
                        echo renderTotalAkun1($lastModel, number_format($totalSebelum1), number_format($totalSesudah1));
                        $totalSebelum1 = 0; $totalSesudah1 = 0;
                    }
                    if($kdAkun1 != $model['kd_rek_1'] && $model['kd_rek_1'] == 7){

                    }
                    if($kdAkun1 != $model['kd_rek_1']) echo renderAkun1($model);
                    if($kdAkun2 != $model['kd_rek_1'].$model['kd_rek_2'] && $kdAkun1 == $model['kd_rek_1'] && $kdAkun2 != 0){
                        echo renderTotalAkun2($lastModel, number_format($totalSebelum2), number_format($totalSesudah2));
                        $totalSebelum2 = 0; $totalSesudah2 = 0;
                    }
                    if($kdAkun2 != $model['kd_rek_1'].$model['kd_rek_2']) echo renderAkun2($model);
            ?>
            <tr> 
                <td><?= $model['kd_rek_1'].$model['kd_rek_2'].$model['kd_rek_3'] ?></td> 
                <td><?= $model['nm_akrual_3'] == '[--Rekening Tidak Terdaftar--]' ? '<code>'.$model['nm_akrual_3'].'</code>' : $model['nm_akrual_3'] ?></td> 
                <td style="text-align:right;"><?= number_format($model['realisasi_sebelum']) ?></td> 
                <td style="text-align:right;"><?= number_format($model['realisasi_sesudah']) ?></td> 
            </tr>
            <?php
                $totalSebelum1 += $model['realisasi_sebelum'];
                $totalSesudah1 += $model['realisasi_sesudah'];
                $totalSebelum2 += $model['realisasi_sebelum'];
                $totalSesudah2 += $model['realisasi_sesudah'];
                if($model['kd_rek_1'] == 4){
                    $totalAkun4Sebelum += $model['realisasi_sebelum'];
                    $totalAkun4Sesudah += $model['realisasi_sesudah'];
                }
                if($model['kd_rek_1'] == 5){
                    $totalAkun5Sebelum += $model['realisasi_sebelum'];
                    $totalAkun5Sesudah += $model['realisasi_sesudah'];
                }
                if($model['kd_rek_1'] == 6 && $model['kd_rek_2'] == 1){
                    $totalAkun61Sebelum += $model['realisasi_sebelum'];
                    $totalAkun61Sesudah += $model['realisasi_sesudah'];
                }
                if($model['kd_rek_1'] == 6 && $model['kd_rek_2'] == 2){
                    $totalAkun62Sebelum += $model['realisasi_sebelum'];
                    $totalAkun62Sesudah += $model['realisasi_sesudah'];
                }
                if($model['kd_rek_1'] == 7 && $model['kd_rek_2'] == 1){
                    $totalAkun71Sebelum += $model['realisasi_sebelum'];
                    $totalAkun71Sesudah += $model['realisasi_sesudah'];
                }
                if($model['kd_rek_1'] == 7 && $model['kd_rek_2'] == 2){
                    $totalAkun72Sebelum += $model['realisasi_sebelum'];
                    $totalAkun72Sesudah += $model['realisasi_sesudah'];
                }
                $kdAkun1 = $model['kd_rek_1'];
                $kdAkun2 = $model['kd_rek_1'].$model['kd_rek_2'];
                $lastModel = $model;
                endforeach;
                echo renderTotalAkun2($lastModel, number_format($totalSebelum2), number_format($totalSesudah2));
                echo renderTotalAkun1($lastModel, number_format($totalAkun71Sebelum-$totalAkun72Sebelum), number_format($totalSesudah1));
            ?>
        </tbody> 
    </table>
</div>

<?php

function renderAkun1($model)
{
    $kdAkun1 = $model['kd_rek_1'];
    $uraian = \app\models\RefAkrual1::findOne(['kd_akrual_1' => $kdAkun1])->nm_akrual_1;
return <<<HTML
<tr> 
    <th>$kdAkun1</th> 
    <th>$uraian</th> 
    <th style="text-align:right;"></th> 
    <!-- <th style="text-align:right;">Eliminasi</th> -->
    <th style="text-align:right;"></th> 
</tr> 
HTML;
}
function renderAkun2($model)
{
    $uraian = '[--Rekening Tidak Terdaftar--]';
    $kdAkun2 = $model['kd_rek_1'].$model['kd_rek_2'];
    $refAkrual2 = \app\models\RefAkrual2::findOne(['kd_akrual_1' => $model['kd_rek_1'], 'kd_akrual_2' => $model['kd_rek_2']]);
    if($refAkrual2) $uraian = $refAkrual2->nm_akrual_2;
return <<<HTML
<tr> 
    <th>$kdAkun2</th> 
    <th>$uraian</th> 
    <th style="text-align:right;"></th> 
    <!-- <th style="text-align:right;">Eliminasi</th> -->
    <th style="text-align:right;"></th> 
</tr> 
HTML;
}
function renderTotalAkun1($model, $totalSebelum, $totalSesudah)
{
    $kdAkun1 = $model['kd_rek_1'];
    $refAkrual1 = \app\models\RefAkrual1::findOne(['kd_akrual_1' => $model['kd_rek_1']]);
    if($refAkrual1) $uraian = $refAkrual1->nm_akrual_1;
return <<<HTML
<tr> 
    <th></th> 
    <th>Total $uraian</th> 
    <th style="text-align:right;">$totalSebelum</th> 
    <!-- <th style="text-align:right;">Eliminasi</th> -->
    <th style="text-align:right;">$totalSesudah</th> 
</tr> 
HTML;
}
function renderTotalAkun2($model, $totalSebelum, $totalSesudah)
{
    $uraian = '[--Rekening Tidak Terdaftar--]';
    $kdAkun2 = $model['kd_rek_1'].$model['kd_rek_2'];
    $refAkrual2 = \app\models\RefAkrual2::findOne(['kd_akrual_1' => $model['kd_rek_1'], 'kd_akrual_2' => $model['kd_rek_2']]);
    if($refAkrual2) $uraian = $refAkrual2->nm_akrual_2;
return <<<HTML
<tr> 
    <th></th> 
    <th>Total $uraian</th> 
    <th style="text-align:right;">$totalSebelum</th> 
    <!-- <th style="text-align:right;">Eliminasi</th> -->
    <th style="text-align:right;">$totalSesudah</th> 
</tr> 
HTML;
}
?>