<?php 

use kartik\grid\GridView;
use yii\helpers\Html;
use yii\bootstrap\Modal;

echo GridView::widget([
	'dataProvider' => $data,
	'responsive'=>true,
	'hover'=>true,     
	'resizableColumns'=>false,
	'panel'=>['type'=>'primary', 'heading'=>$heading],
	'responsiveWrap' => false,     
	'toolbar' => [
            '{toggleData}',
            '{export}',
    ],
    'exportConfig' => [
        GridView::HTML => ['filename' => $heading,],
        GridView::CSV => ['filename' => $heading,],
        GridView::TEXT => ['filename' => $heading,],
        GridView::EXCEL => ['filename' => $heading,], 
        GridView::PDF => [
            'label' => 'PDF',
            'showHeader' => true,
            'showPageSummary' => true,
            'showFooter' => true,
            'showCaption' => true,
            'filename' => $heading,
            'alertMsg' => 'The PDF export file will be generated for download.',
            'options' => ['title' => 'Portable Document Format'],
            'mime' => 'application/pdf',
            'config' => [
                'mode' => 'c',
                'format' => 'A4-L',
                'destination' => 'D',
                'marginTop' => 20,
                'marginBottom' => 20,
                'cssInline' => '.kv-wrap{padding:20px;}' .
                    '.kv-align-center{text-align:center;}' .
                    '.kv-align-left{text-align:left;}' .
                    '.kv-align-right{text-align:right;}' .
                    '.kv-align-top{vertical-align:top!important;}' .
                    '.kv-align-bottom{vertical-align:bottom!important;}' .
                    '.kv-align-middle{vertical-align:middle!important;}' .
                    '.kv-page-summary{border-top:4px double #ddd;font-weight: bold;}' .
                    '.kv-table-footer{border-top:4px double #ddd;font-weight: bold;}' .
                    '.kv-table-caption{font-size:1.5em;padding:8px;border:1px solid #ddd;border-bottom:none;}',
                'methods' => [
                    'SetHeader' => $heading,
                    'SetFooter' => '<li role="presentation" class="dropdown-footer">Generated by econsole, '.date('Y-m-d H-i-s T').'</li>',
                ],
                'options' => [
                    'title' => $heading,
                    'subject' => 'PDF export generated by econsole',
                    'keywords' => 'grid, export, yii2-grid, pdf'
                ],
                'contentBefore'=>'',
                'contentAfter'=>''
            ]
        ],
        GridView::JSON => ['filename' => $heading,],
    ],
	'pager' => [
	    'firstPageLabel' => 'Awal',
	    'lastPageLabel'  => 'Akhir'
	],
	'pjax'=>true,
	'pjaxSettings'=>[
	    'options' => ['id' => 'laporan1-pjax', 'timeout' => 5000],
	],
	// 'showPageSummary'=>true,    
	'columns' => [
        [
            'label' => 'Kode',
            'attribute' => 'id'
        ],
        [
            'label' => 'Nama Pemda',
            'attribute' => 'nama_pemda'
        ],
        [
            'label' => substr(\app\models\Periode::findOne(['id' => 0])['name'],0,3),
            'format' => 'raw',
            'hAlign' => 'center',
            'value' => function($model){
                if($model['col_0'] != NULL) return '<span class="label label-success"><i class="glyphicon glyphicon-ok"> 1</i></span>';
                return '<span class="label label-danger"><i class="glyphicon glyphicon-remove"></i></span>';
            }
        ],
        [
            'label' => substr(\app\models\Periode::findOne(['id' => 1])['name'],0,3),
            'format' => 'raw',
            'hAlign' => 'center',
            'value' => function($model){
                if($model['col_1'] != NULL) return '<span class="label label-success"><i class="glyphicon glyphicon-ok"> 1</i></span>';
                return '<span class="label label-danger"><i class="glyphicon glyphicon-remove"></i></span>';
            }
        ],
        [
            'label' => substr(\app\models\Periode::findOne(['id' => 2])['name'],0,3),
            'format' => 'raw',
            'hAlign' => 'center',
            'value' => function($model){
                if($model['col_2'] != NULL) return '<span class="label label-success"><i class="glyphicon glyphicon-ok"> 1</i></span>';
                return '<span class="label label-danger"><i class="glyphicon glyphicon-remove"></i></span>';
            }
        ],
        [
            'label' => substr(\app\models\Periode::findOne(['id' => 3])['name'],0,3),
            'format' => 'raw',
            'hAlign' => 'center',
            'value' => function($model){
                if($model['col_3'] != NULL) return '<span class="label label-success"><i class="glyphicon glyphicon-ok"> 1</i></span>';
                return '<span class="label label-danger"><i class="glyphicon glyphicon-remove"></i></span>';
            }
        ],
        [
            'label' => substr(\app\models\Periode::findOne(['id' => 4])['name'],0,3),
            'format' => 'raw',
            'hAlign' => 'center',
            'value' => function($model){
                if($model['col_4'] != NULL) return '<span class="label label-success"><i class="glyphicon glyphicon-ok"> 1</i></span>';
                return '<span class="label label-danger"><i class="glyphicon glyphicon-remove"></i></span>';
            }
        ],
        [
            'label' => substr(\app\models\Periode::findOne(['id' => 5])['name'],0,3),
            'format' => 'raw',
            'hAlign' => 'center',
            'value' => function($model){
                if($model['col_5'] != NULL) return '<span class="label label-success"><i class="glyphicon glyphicon-ok"> 1</i></span>';
                return '<span class="label label-danger"><i class="glyphicon glyphicon-remove"></i></span>';
            }
        ],
        [
            'label' => substr(\app\models\Periode::findOne(['id' => 6])['name'],0,3),
            'format' => 'raw',
            'hAlign' => 'center',
            'value' => function($model){
                if($model['col_6'] != NULL) return '<span class="label label-success"><i class="glyphicon glyphicon-ok"> 1</i></span>';
                return '<span class="label label-danger"><i class="glyphicon glyphicon-remove"></i></span>';
            }
        ],
        [
            'label' => substr(\app\models\Periode::findOne(['id' => 7])['name'],0,3),
            'format' => 'raw',
            'hAlign' => 'center',
            'value' => function($model){
                if($model['col_7'] != NULL) return '<span class="label label-success"><i class="glyphicon glyphicon-ok"> 1</i></span>';
                return '<span class="label label-danger"><i class="glyphicon glyphicon-remove"></i></span>';
            }
        ],
        [
            'label' => substr(\app\models\Periode::findOne(['id' => 8])['name'],0,3),
            'format' => 'raw',
            'hAlign' => 'center',
            'value' => function($model){
                if($model['col_8'] != NULL) return '<span class="label label-success"><i class="glyphicon glyphicon-ok"> 1</i></span>';
                return '<span class="label label-danger"><i class="glyphicon glyphicon-remove"></i></span>';
            }
        ],
        [
            'label' => substr(\app\models\Periode::findOne(['id' => 9])['name'],0,3),
            'format' => 'raw',
            'hAlign' => 'center',
            'value' => function($model){
                if($model['col_9'] != NULL) return '<span class="label label-success"><i class="glyphicon glyphicon-ok"> 1</i></span>';
                return '<span class="label label-danger"><i class="glyphicon glyphicon-remove"></i></span>';
            }
        ],
        [
            'label' => substr(\app\models\Periode::findOne(['id' => 10])['name'],0,3),
            'format' => 'raw',
            'hAlign' => 'center',
            'value' => function($model){
                if($model['col_10'] != NULL) return '<span class="label label-success"><i class="glyphicon glyphicon-ok"> 1</i></span>';
                return '<span class="label label-danger"><i class="glyphicon glyphicon-remove"></i></span>';
            }
        ],
        [
            'label' => substr(\app\models\Periode::findOne(['id' => 11])['name'],0,3),
            'format' => 'raw',
            'hAlign' => 'center',
            'value' => function($model){
                if($model['col_11'] != NULL) return '<span class="label label-success"><i class="glyphicon glyphicon-ok"> 1</i></span>';
                return '<span class="label label-danger"><i class="glyphicon glyphicon-remove"></i></span>';
            }
        ],
        [
            'label' => substr(\app\models\Periode::findOne(['id' => 12])['name'],0,3),
            'format' => 'raw',
            'hAlign' => 'center',
            'value' => function($model){
                if($model['col_12'] != NULL) return '<span class="label label-success"><i class="glyphicon glyphicon-ok"> 1</i></span>';
                return '<span class="label label-danger"><i class="glyphicon glyphicon-remove"></i></span>';
            }
        ],
        [
            'label' => substr(\app\models\Periode::findOne(['id' => 13])['name'],0,3),
            'format' => 'raw',
            'hAlign' => 'center',
            'value' => function($model){
                if($model['col_13'] != NULL) return '<span class="label label-success"><i class="glyphicon glyphicon-ok"> 1</i></span>';
                return '<span class="label label-danger"><i class="glyphicon glyphicon-remove"></i></span>';
            }
        ],
        [
            'label' => substr(\app\models\Periode::findOne(['id' => 14])['name'],0,3),
            'format' => 'raw',
            'hAlign' => 'center',
            'value' => function($model){
                if($model['col_14'] != NULL) return '<span class="label label-success"><i class="glyphicon glyphicon-ok"> 1</i></span>';
                return '<span class="label label-danger"><i class="glyphicon glyphicon-remove"></i></span>';
            }
        ],
        [
            'label' => substr(\app\models\Periode::findOne(['id' => 15])['name'],0,3),
            'format' => 'raw',
            'hAlign' => 'center',
            'value' => function($model){
                if($model['col_15'] != NULL) return '<span class="label label-success"><i class="glyphicon glyphicon-ok"> 1</i></span>';
                return '<span class="label label-danger"><i class="glyphicon glyphicon-remove"></i></span>';
            }
        ],
        [
            'label' => substr(\app\models\Periode::findOne(['id' => 16])['name'],0,3),
            'format' => 'raw',
            'hAlign' => 'center',
            'value' => function($model){
                if($model['col_16'] != NULL) return '<span class="label label-success"><i class="glyphicon glyphicon-ok"> 1</i></span>';
                return '<span class="label label-danger"><i class="glyphicon glyphicon-remove"></i></span>';
            }
        ],
        // [
        //     'attribute' => 'realisasi_sesudah',
        //     'label' => 'Sesudah Eliminasi',
        //     'format' => 'decimal',
        //     'hAlign' => 'right',
        //     // 'pageSummary' => true,
        //     'value' => function($model){
        //         return $model['realisasi_sesudah'] ? $model['realisasi_sesudah'] : 0;
        //     }
        // ],
	],
]); 
 ?>
 <?php
 Modal::begin([
    'id' => 'myModal',
    'header' => '<h4 class="modal-title">Lihat lebih...</h4>',
    'options' => [
        'tabindex' => false // important for Select2 to work properly
    ], 
    'size' => 'modal-lg'
]);
 
echo '...';
 
Modal::end();
$this->registerJs("
    $('#myModal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget)
        var modal = $(this)
        var title = button.data('title') 
        var href = button.attr('href') 
        modal.find('.modal-title').html(title)
        modal.find('.modal-body').html('<i class=\"fa fa-spinner fa-spin\"></i>')
        $.post(href)
            .done(function( data ) {
                modal.find('.modal-body').html(data)
            });
        })
");
$this->registerCss(<<<CSS
    a.akunDetail{
        color:inherit;
    }
CSS
);
?>