<?php 

use kartik\grid\GridView;
use yii\helpers\Html;
use yii\bootstrap\Modal;

echo GridView::widget([
    'dataProvider' => $data,
    'filterModel' => $data1,
	'responsive'=>true,
	'hover'=>true,     
	'resizableColumns'=>false,
	'panel'=>['type'=>'primary', 'heading'=>$heading],
	'responsiveWrap' => false,        
	'toolbar' => [
            '{toggleData}',
            '{export}',   
    ],
    'exportConfig' => [
        GridView::HTML => ['filename' => $heading,],
        GridView::CSV => ['filename' => $heading,],
        GridView::TEXT => ['filename' => $heading,],
        GridView::EXCEL => ['filename' => $heading,], 
        GridView::PDF => [
            'label' => 'PDF',
            'showHeader' => true,
            'showPageSummary' => true,
            'showFooter' => true,
            'showCaption' => true,
            'filename' => $heading,
            'alertMsg' => 'The PDF export file will be generated for download.',
            'options' => ['title' => 'Portable Document Format'],
            'mime' => 'application/pdf',
            'config' => [
                'mode' => 'c',
                'format' => 'A4-L',
                'destination' => 'D',
                'marginTop' => 20,
                'marginBottom' => 20,
                'cssInline' => '.kv-wrap{padding:20px;}' .
                    '.kv-align-center{text-align:center;}' .
                    '.kv-align-left{text-align:left;}' .
                    '.kv-align-right{text-align:right;}' .
                    '.kv-align-top{vertical-align:top!important;}' .
                    '.kv-align-bottom{vertical-align:bottom!important;}' .
                    '.kv-align-middle{vertical-align:middle!important;}' .
                    '.kv-page-summary{border-top:4px double #ddd;font-weight: bold;}' .
                    '.kv-table-footer{border-top:4px double #ddd;font-weight: bold;}' .
                    '.kv-table-caption{font-size:1.5em;padding:8px;border:1px solid #ddd;border-bottom:none;}',
                'methods' => [
                    'SetHeader' => $heading,
                    'SetFooter' => '<li role="presentation" class="dropdown-footer">Generated by econsole, '.date('Y-m-d H-i-s T').'</li>',
                ],
                'options' => [
                    'title' => $heading,
                    'subject' => 'PDF export generated by econsole',
                    'keywords' => 'grid, export, yii2-grid, pdf'
                ],
                'contentBefore'=>'',
                'contentAfter'=>''
            ]
        ],
        GridView::JSON => ['filename' => $heading,],
    ],
	'pager' => [
	    'firstPageLabel' => 'Awal',
	    'lastPageLabel'  => 'Akhir'
	],
	'pjax'=>true,
	'pjaxSettings'=>[
	    'options' => ['id' => 'laporan1-pjax', 'timeout' => 5000],
	],
	'showPageSummary'=>true,    
	'columns' => [
        [
            'label' => 'Kode',
            'attribute' => 'id',
        ],
        [
            'label' => 'Nama Pemda',
            'attribute' => 'name'
        ],
        [
            'label' => 'Akun Dieliminasi',
            'attribute' => 'province_id',
            'filter' => Html::textInput('MonitoringEliminasiSearch[akun_eliminasi]', $data1->akun_eliminasi ? $data1->akun_eliminasi : null, ['class' => 'form-control'] ),
            // 'filterOptions ' =>[
            //     'name' => 'MonitoringEliminasiSearch[akun_eliminasi]'
            // ]
            // 'filter' => Select2::widget([
            //     'name' => 'ObjectSearch[countryId]',
            //     'data' => Country::forWidgets(),
            //     'theme' => Select2::THEME_BOOTSTRAP,
            //     'options' => [
            //         'placeholder' => 'Wybierz państwo...'
            //     ]
            //  ]),
        ],
	],
]); 
 ?>
 <?php
 Modal::begin([
    'id' => 'myModal',
    'header' => '<h4 class="modal-title">Lihat lebih...</h4>',
    'options' => [
        'tabindex' => false // important for Select2 to work properly
    ], 
    'size' => 'modal-lg'
]);
 
echo '...';
 
Modal::end();
$this->registerJs("
    $('#myModal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget)
        var modal = $(this)
        var title = button.data('title') 
        var href = button.attr('href') 
        modal.find('.modal-title').html(title)
        modal.find('.modal-body').html('<i class=\"fa fa-spinner fa-spin\"></i>')
        $.post(href)
            .done(function( data ) {
                modal.find('.modal-body').html(data)
            });
        })
");
$this->registerCss(<<<CSS
    a.akunDetail{
        color:inherit;
    }
CSS
);
?>