<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\widgets\Pjax;
use xj\bootbox\BootboxAsset;
use yii\bootstrap\Modal;
use yii\web\Controller;
?>
<?php // echo $this->render('_search', ['model' => $searchModel]); ?>

<?php 
    echo GridView::widget([
        'dataProvider' => $data,
        //'filterModel' => $searchModel,
        // 'export' => true, 
        'responsive'=>true,
        'hover'=>true,     
        'resizableColumns'=>false,
        'panel'=>['type'=>'primary', 'heading'=> $heading       
        ],
        'responsiveWrap' => false,        
        'toolbar' => [
            '{toggleData}',
            '{export}',
        ],
        'exportConfig' => [
            GridView::HTML => ['filename' => $heading,],
            GridView::CSV => ['filename' => $heading,],
            GridView::TEXT => ['filename' => $heading,],
            GridView::EXCEL => ['filename' => $heading,], 
            GridView::PDF => [
                'label' => 'PDF',
                'showHeader' => true,
                'showPageSummary' => true,
                'showFooter' => true,
                'showCaption' => true,
                'filename' => $heading,
                'alertMsg' => 'The PDF export file will be generated for download.',
                'options' => ['title' => 'Portable Document Format'],
                'mime' => 'application/pdf',
                'config' => [
                    'mode' => 'c',
                    'format' => 'A4-L',
                    'destination' => 'D',
                    'marginTop' => 20,
                    'marginBottom' => 20,
                    'cssInline' => '.kv-wrap{padding:20px;}' .
                        '.kv-align-center{text-align:center;}' .
                        '.kv-align-left{text-align:left;}' .
                        '.kv-align-right{text-align:right;}' .
                        '.kv-align-top{vertical-align:top!important;}' .
                        '.kv-align-bottom{vertical-align:bottom!important;}' .
                        '.kv-align-middle{vertical-align:middle!important;}' .
                        '.kv-page-summary{border-top:4px double #ddd;font-weight: bold;}' .
                        '.kv-table-footer{border-top:4px double #ddd;font-weight: bold;}' .
                        '.kv-table-caption{font-size:1.5em;padding:8px;border:1px solid #ddd;border-bottom:none;}',
                    'methods' => [
                        'SetHeader' => $heading,
                        'SetFooter' => '<li role="presentation" class="dropdown-footer">Generated by SIAPDa-Aceh, '.date('Y-m-d H-i-s T').'</li>',
                    ],
                    'options' => [
                        'title' => $heading,
                        'subject' => 'PDF export generated by SIAPDa-Aceh',
                        'keywords' => 'grid, export, yii2-grid, pdf'
                    ],
                    'contentBefore'=>'',
                    'contentAfter'=>''
                ]
            ],
            GridView::JSON => ['filename' => $heading,],
        ],          
        'pager' => [
            'firstPageLabel' => 'Awal',
            'lastPageLabel'  => 'Akhir'
        ],
        'pjax'=>true,
        'pjaxSettings'=>[
            'options' => ['id' => 'laporan1-pjax', 'timeout' => 5000],
        ],
        'showPageSummary'=>true,         
        'columns' => [
            // a.id, a.name, a.opini, a.sakip, a.lppd, a.spip, a.kasus, a.pilkada, 
            //                     (IFNULL(a.opini, 0) + a.sakip + a.lppd + a.spip + a.kasus + a.pilkada) AS skor      
            [
                'label' => 'Pemda',
                'value' =>function($model){
                    return $model['name'];
                },
                // 'group'=>true,  // enable grouping,
                // 'groupedRow'=>true,                    // move grouped column to a single grouped row
                // 'groupOddCssClass'=>'kv-grouped-row',  // configure odd group cell css class
                // 'groupEvenCssClass'=>'kv-grouped-row', // configure even group cell css class
            ],
            'opini',
            'sakip',
            'lppd',
            'spip',
            'kasus',
            'pilkada',
            'skor'
            // [
            //     'label' => 'Alokasi Jumlah Desa',
            //     'value' => function($model){
            //         $model['jumlah_desa_alokasi'];
            //     }
            // ],
            // [
            //     'label' => 'Alokasi Nilai',
            //     'format' => 'decimal',
            //     'value' => function($model){
            //         $model['nilai_alokasi'];
            //     }
            // ],
            // [
            //     'label' => 'Jumlah Desa Disalurkan ke RKUD',
            //     'value' => function($model){
            //         $model['jumlah_desa_rkud'];
            //     }
            // ],
            // [
            //     'label' => 'Nilai Disalurkan ke RKUD',
            //     'format' => 'decimal',
            //     'value' => function($model){
            //         $model['nilai_rkud'];
            //     }
            // ],
            // [
            //     'label' => 'Jumlah Desa Disalurkan ke RKUDesa',
            //     'value' => function($model){
            //         $model['jumlah_desa_rkudesa'];
            //     }
            // ],
            // [
            //     'label' => 'Nilai Disalurkan ke RKUDesa',
            //     'format' => 'decimal',
            //     'value' => function($model){
            //         $model['nilai_rkudesa'];
            //     }
            // ],
            // [
            //     'label' => 'Siskeudes',
            //     'value' => function($model){
            //         $model['jumlah_desa_implementasi'];
            //     }
            // ],
            // [
            //     'label' => 'Kompilasi dgn Siskeudes',
            //     'format' => 'raw',
            //     'value' => function($model){
            //         if($model['kompilasi'] == 1) return '<span class="label label-success"><i class="glyphicon glyphicon-ok"> 1</i></span>';
            //         return '<span class="label label-danger"><i class="glyphicon glyphicon-remove"></i></span>';
            //     }
            // ],
        ],
    ]); 
?>
