<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\widgets\Pjax;
use xj\bootbox\BootboxAsset;
use yii\bootstrap\Modal;
use yii\web\Controller;
?>
<?php // echo $this->render('_search', ['model' => $searchModel]); ?>

<?php 
    echo GridView::widget([
        'dataProvider' => $data,
        //'filterModel' => $searchModel,
        // 'export' => true, 
        'responsive'=>true,
        'hover'=>true,     
        'resizableColumns'=>false,
        'panel'=>['type'=>'primary', 'heading'=> $heading       
        ],
        'responsiveWrap' => false,        
        'toolbar' => [
            '{toggleData}',
            '{export}',
        ],
        'exportConfig' => [
            GridView::HTML => ['filename' => $heading,],
            GridView::CSV => ['filename' => $heading,],
            GridView::TEXT => ['filename' => $heading,],
            GridView::EXCEL => ['filename' => $heading,], 
            GridView::PDF => [
                'label' => 'PDF',
                'showHeader' => true,
                'showPageSummary' => true,
                'showFooter' => true,
                'showCaption' => true,
                'filename' => $heading,
                'alertMsg' => 'The PDF export file will be generated for download.',
                'options' => ['title' => 'Portable Document Format'],
                'mime' => 'application/pdf',
                'config' => [
                    'mode' => 'c',
                    'format' => 'A4-L',
                    'destination' => 'D',
                    'marginTop' => 20,
                    'marginBottom' => 20,
                    'cssInline' => '.kv-wrap{padding:20px;}' .
                        '.kv-align-center{text-align:center;}' .
                        '.kv-align-left{text-align:left;}' .
                        '.kv-align-right{text-align:right;}' .
                        '.kv-align-top{vertical-align:top!important;}' .
                        '.kv-align-bottom{vertical-align:bottom!important;}' .
                        '.kv-align-middle{vertical-align:middle!important;}' .
                        '.kv-page-summary{border-top:4px double #ddd;font-weight: bold;}' .
                        '.kv-table-footer{border-top:4px double #ddd;font-weight: bold;}' .
                        '.kv-table-caption{font-size:1.5em;padding:8px;border:1px solid #ddd;border-bottom:none;}',
                    'methods' => [
                        'SetHeader' => $heading,
                        'SetFooter' => '<li role="presentation" class="dropdown-footer">Generated by SIAPDa-Aceh, '.date('Y-m-d H-i-s T').'</li>',
                    ],
                    'options' => [
                        'title' => $heading,
                        'subject' => 'PDF export generated by SIAPDa-Aceh',
                        'keywords' => 'grid, export, yii2-grid, pdf'
                    ],
                    'contentBefore'=>'',
                    'contentAfter'=>''
                ]
            ],
            GridView::JSON => ['filename' => $heading,],
        ],          
        'pager' => [
            'firstPageLabel' => 'Awal',
            'lastPageLabel'  => 'Akhir'
        ],
        'pjax'=>true,
        'pjaxSettings'=>[
            'options' => ['id' => 'laporan1-pjax', 'timeout' => 5000],
        ],
        'showPageSummary'=>true,         
        'columns' => [
            // ['class' => 'kartik\grid\SerialColumn'],            
            [
                'label' => 'Pemda',
                'value' =>function($model){
                    return $model['name'];
                },
                // 'group'=>true,  // enable grouping,
                // 'groupedRow'=>true,                    // move grouped column to a single grouped row
                // 'groupOddCssClass'=>'kv-grouped-row',  // configure odd group cell css class
                // 'groupEvenCssClass'=>'kv-grouped-row', // configure even group cell css class
            ],
            [
                'label' => 'Tanggal Penyampaian',
                'format' => 'date',
                'value' => function($model){
                    return $model['tanggal'];
                }
            ],
            [
                'label' => 'Kategori',
                'value' => function($model) use($tahun){
                    return $model['status'];
                }
            ],
            [
                'label' => 'Pihak Membantu Penyusunan',
                'value' => function($model){
                    return $model['pihak_bantu'];
                }
            ],
            [
                'label' => 'Opini',
                'value' => function($model){
                    return $model['opini'];
                }
            ],
            [
                'label' => 'SIMDA',
                'value' => function($model){
                    return $model['simda'];
                }
            ],
            'ket'
        ],
    ]); 
?>
